Refactor/upgrade and swap fully to react query
bcgsc/pori_graphkb_client pull request #35
Opened 2022-02-03 23:43 UTC by areisle

closes #27 

this removes all leftover dependencies on abort controllers and swaps them to react query
it also updates to react-query v3 to be able to take advantage of the `select` option

I did a fair bit of manual testing for this PR which I've listed below:
#### statements
* [x] can create (and all auto-completes working)
* [x] can update
* [x] can delete
* [x] can view

#### records
* [x] can create
* [x] can update
* [x] can delete
* [x] can view

#### about
* [x] all pages load without error
* [x] can sign license and shows correct state of signed vs not signed

#### query
* [x] can search for term and takes you to data view

#### advanced query
* [x] all auto-completes work
* [x] can search and takes you to data view

#### admin
* [x] users/groups load without error
* [x] can add user
* cant add group (same as develop, see #34)

 if there's any other cases you feel should manually be tested let me know

2022-02-05 00:33 UTC, elewis2 approved these changes

2022-02-10 21:22 UTC, areisle commented
@kttkjl @creisle are either of you wanting to look at this before I merge?

2022-02-10 22:29 UTC, creisle requested changes
Fix login errors

2022-02-11 19:48 UTC, areisle commented
I have fixed the auth issue and another I found retesting with the graph, and have retested the entire checklist. I also rebased to get latest commits from develop before retesting

2022-02-11 22:41 UTC, creisle commented
Almost all the pages I tested work now
- [ ] create a statement
- [ ] create an ontology term
- [ ] create a source
- [ ] update an ontology term
- [ ] update a statement
- [ ] update a source
- [ ] delete a statement
- [ ] delete an ontology term
- [ ] delete a source
- [ ] add a user
- [ ] update a user
- [ ] import a pubmed article
- [ ] advanced search
- [ ] basic search

But the import page is broken, you cannot navigate to it at all. I've attached the console log
[creisle04.phage.bcgsc.ca-1644619270892.log](https://github.com/bcgsc/pori_graphkb_client/files/8052048/creisle04.phage.bcgsc.ca-1644619270892.log)

2022-02-11 23:03 UTC, areisle commented
> But the import page is broken, you cannot navigate to it at all. I've attached the console log

[14b4c18](https://github.com/bcgsc/pori_graphkb_client/pull/35/commits/14b4c18a2bd3092c6e99dfe3175ca26cf365531d)

2022-02-11 23:22 UTC, merged